//
//  TodayRouter.swift
//  TodayInHistory
//
//  Created by mac on 9.02.2020.
//  Copyright (c) 2020 Alaattin Bedir. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol TodayRoutingLogic
{
  
}

protocol TodayDataPassing
{
  var dataStore: TodayDataStore? { get }
}

class TodayRouter: NSObject, TodayRoutingLogic, TodayDataPassing
{
  weak var viewController: TodayViewController?
  var dataStore: TodayDataStore?
}
