//
//  TodayModels.swift
//  TodayInHistory
//
//  Created by mac on 9.02.2020.
//  Copyright (c) 2020 Alaattin Bedir. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ListToday
{
  // MARK: Data structure for Clean Swift design patern
  enum FetchToday
  {
    struct Request
    {
    }
    
    struct Response : Codable
    {
      var today: Today?      
    }
    
    struct ViewModel
    {
      var displayedEvents: [TodayData]
      var displayedBirths: [TodayData]
      var displayedDeaths: [TodayData]
    }
        
  }
}
