//
//  TodayPresenter.swift
//  TodayInHistory
//
//  Created by mac on 9.02.2020.
//  Copyright (c) 2020 Alaattin Bedir. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TodayPresentationLogic
{
  func presentSomething(response: Today.Something.Response)
  func presentSomething2(response: Today.Something.Response.Today)
}

class TodayPresenter: TodayPresentationLogic
{
  weak var viewController: TodayDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething2(response: Today.Something.Response.Today)
  {
    let viewModel = Today.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
    
    func presentSomething(response: Today.Something.Response) {
        let viewModel = Today.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
    

}
