//
//  TodayModels.swift
//  TodayInHistory
//
//  Created by mac on 9.02.2020.
//  Copyright (c) 2020 Alaattin Bedir. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Today
{
  // MARK: Use cases
  
  enum Something
  {
    struct Request
    {
    }
    struct Response: Codable
    {
        // MARK: - Today
        struct Today: Codable {
            let date: String
            let url: String
            let data: DataClass
        }

        // MARK: - DataClass
        struct DataClass: Codable {
            let events, births, deaths: [Birth]

            enum CodingKeys: String, CodingKey {
                case events = "Events"
                case births = "Births"
                case deaths = "Deaths"
            }
        }

        // MARK: - Birth
        struct Birth: Codable {
            let year, text, html, noYearHTML: String
            let links: [Link]

            enum CodingKeys: String, CodingKey {
                case year, text, html
                case noYearHTML = "no_year_html"
                case links
            }
        }

        // MARK: - Link
        struct Link: Codable {
            let title: String
            let link: String
        }
    }
    
    
    
    struct ViewModel
    {
      var today: Today?
    }
    
    
    
    
  }
}
