//
//  TodayViewController.swift
//  TodayInHistory
//
//  Created by mac on 9.02.2020.
//  Copyright (c) 2020 Alaattin Bedir. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TodayDisplayLogic: class
{
  func displayTodayData(viewModel: ListToday.FetchToday.ViewModel)
}

enum Options {
  case events
  case births
  case deaths
}

class TodayViewController: UIViewController, TodayDisplayLogic
{
  var interactor: TodayBusinessLogic?
  var router: (NSObjectProtocol & TodayRoutingLogic & TodayDataPassing)?
  var displayedData: [TodayData] = []
  var selectedOption: Options = .events
  
  let eventCellNibName = "EventTableViewCell"
  let eventCellIdentifier = "EventCellIdentifier"
  
  let deathCellNibName = "DeathTableViewCell"
  let deathCellIdentifier = "DeathCellIdentifier"
  
  let birthCellNibName = "BirthTableViewCell"
  let birthCellIdentifier = "BirthCellIdentifier"
  
  @IBOutlet weak var tableView: UITableView!
  @IBOutlet weak var optionsSegmentedControl: UISegmentedControl!
  
  @IBAction func optionsChanged(_ sender: Any) {
    switch optionsSegmentedControl.selectedSegmentIndex
    {
      case 0:
        selectedOption = .events
        case 1:
        selectedOption = .births
        case 2:
        selectedOption = .deaths
        default:
          break
    }
    
    fetchTodayInHistory()    
  }
  
  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = TodayInteractor()
    let presenter = TodayPresenter()
    let router = TodayRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  func prepareTableView() {
      tableView.dataSource = self
      tableView.delegate = self
      tableView.contentInset = UIEdgeInsets(top: 0.0, left: 0.0, bottom: 0.0, right: 0.0)
      tableView.rowHeight = UITableView.automaticDimension
      tableView.estimatedRowHeight = 44
      tableView.register(UINib.init(nibName: eventCellNibName, bundle: nil), forCellReuseIdentifier: eventCellIdentifier)
      tableView.register(UINib.init(nibName: deathCellNibName, bundle: nil), forCellReuseIdentifier: deathCellIdentifier)
      tableView.register(UINib.init(nibName: birthCellNibName, bundle: nil), forCellReuseIdentifier: birthCellIdentifier)
  }
  
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    prepareTableView()
  }
  
  override func viewWillAppear(_ animated: Bool)
  {
    super.viewWillAppear(animated)
    fetchTodayInHistory()
  }
  
  // MARK: Fetch today in the history data
  
  func fetchTodayInHistory()
  {
    let request = ListToday.FetchToday.Request()
    interactor?.fetchTodayInHistory(request: request)
  }
  
  func displayTodayData(viewModel: ListToday.FetchToday.ViewModel)
  {
    switch selectedOption
    {
      case .events:
        displayedData = viewModel.displayedEvents
      case .births:
        displayedData = viewModel.displayedBirths
      case .deaths:
        displayedData = viewModel.displayedDeaths
    }
    
    DispatchQueue.main.async {
        self.tableView.reloadData()
    }
  }
}

