//
//  TodayWorker.swift
//  TodayInHistory
//
//  Created by mac on 9.02.2020.
//  Copyright (c) 2020 Alaattin Bedir. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class TodayWorker
{
    func doSomeWork()
    {
    }
    
  func fetchTodayInHistory(completion: @escaping (Today.Something.Response.Today?, Error?) -> ())
    {
        guard let publicUrl = URL(string: APPURL.BaseURL) else { return }
        URLSession.shared.dataTask(with: publicUrl) { (data, response, error) in
            guard let data = data else { return }
            do {
                let decoder = JSONDecoder()
              let publicData = try decoder.decode(Today.Something.Response.Today.self, from: data)
                print(publicData)
                completion(publicData,nil)
            } catch let err {
                print("Error", err)
                completion(nil,err)
            }
            }.resume()
    }
}
