//
//  TodayPresenter.swift
//  TodayInHistory
//
//  Created by mac on 9.02.2020.
//  Copyright (c) 2020 Alaattin Bedir. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TodayPresentationLogic
{
  func presentSomething(response: ListToday.FetchToday.Response)
  func presentFetchedToday(response: ListToday.FetchToday.Response)
}

class TodayPresenter: TodayPresentationLogic
{
  weak var viewController: TodayDisplayLogic?
  
  // MARK: Do something
  
  func presentFetchedToday(response: ListToday.FetchToday.Response)
  {
    let displayedEvents: [ListToday.FetchToday.ViewModel.Event] = []
    let viewModel = ListToday.FetchToday.ViewModel(displayedEvents: displayedEvents)
    viewController?.displaySomething(viewModel: viewModel)
  }
    
  func presentSomething(response: ListToday.FetchToday.Response) {
      let displayedEvents: [ListToday.FetchToday.ViewModel.Event] = []
        let viewModel = ListToday.FetchToday.ViewModel(displayedEvents: displayedEvents)
        viewController?.displaySomething(viewModel: viewModel)
    }
    

}
